export default [
  {
    id: 1,
    title: 'ユーザー認証機能の実装',
    description: 'JWT認証システムを構築し、ログイン/ログアウト機能を実装する',
    status: '進行中',
    priority: '高',
    progress: 65,
    assignee: '田中太郎',
    dueDate: '2024-12-20',
  },
  {
    id: 2,
    title: 'データベース設計',
    description: 'アプリケーションのデータベーススキーマを設計する',
    status: '完了',
    priority: '高',
    progress: 100,
    assignee: '佐藤花子',
    dueDate: '2024-12-10',
  },
  {
    id: 3,
    title: 'UI/UXデザインレビュー',
    description: '新しいデザインシステムのレビューとフィードバック',
    status: '未着手',
    priority: '中',
    progress: 0,
    assignee: '鈴木一郎',
    dueDate: '2024-12-25',
  },
  {
    id: 4,
    title: 'APIドキュメント作成',
    description: 'RESTful APIのドキュメントをSwaggerで作成する',
    status: '進行中',
    priority: '中',
    progress: 40,
    assignee: '高橋美咲',
    dueDate: '2024-12-22',
  },
  {
    id: 5,
    title: 'パフォーマンス最適化',
    description: 'アプリケーションの読み込み速度を改善する',
    status: '未着手',
    priority: '低',
    progress: 0,
    assignee: '伊藤健太',
    dueDate: '2024-12-30',
  },
  {
    id: 6,
    title: 'セキュリティ監査',
    description: 'アプリケーション全体のセキュリティ脆弱性をチェック',
    status: '進行中',
    priority: '高',
    progress: 80,
    assignee: '山田次郎',
    dueDate: '2024-12-18',
  },
  {
    id: 7,
    title: 'テストケース作成',
    description: 'E2Eテストとユニットテストのケースを作成',
    status: '進行中',
    priority: '中',
    progress: 55,
    assignee: '中村真理',
    dueDate: '2024-12-23',
  },
  {
    id: 8,
    title: 'モバイル対応',
    description: 'レスポンシブデザインでモバイル端末に対応',
    status: '未着手',
    priority: '中',
    progress: 0,
    assignee: '小林直樹',
    dueDate: '2024-12-28',
  },
  {
    id: 9,
    title: 'ダークモード実装',
    description: 'アプリケーション全体にダークモードを追加',
    status: '完了',
    priority: '低',
    progress: 100,
    assignee: '加藤さくら',
    dueDate: '2024-12-15',
  },
  {
    id: 10,
    title: 'メール通知機能',
    description: 'タスク更新時のメール通知機能を実装',
    status: '未着手',
    priority: '低',
    progress: 0,
    assignee: '渡辺康平',
    dueDate: '2024-12-31',
  },
  {
    id: 11,
    title: 'ファイルアップロード機能',
    description: '画像やドキュメントのアップロード機能を追加',
    status: '進行中',
    priority: '高',
    progress: 75,
    assignee: '田中太郎',
    dueDate: '2024-12-19',
  },
  {
    id: 12,
    title: 'i18n対応',
    description: '多言語対応のための国際化機能を実装',
    status: '未着手',
    priority: '中',
    progress: 0,
    assignee: '佐藤花子',
    dueDate: '2025-01-05',
  },
  {
    id: 13,
    title: 'CI/CDパイプライン構築',
    description: 'GitHub Actionsを使用した自動デプロイメントの設定',
    status: '進行中',
    priority: '高',
    progress: 70,
    assignee: '木村拓哉',
    dueDate: '2024-12-21',
  },
  {
    id: 14,
    title: 'エラーログ監視システム',
    description: 'Sentryを導入してエラートラッキングを実装',
    status: '未着手',
    priority: '中',
    progress: 0,
    assignee: '松本潤',
    dueDate: '2024-12-27',
  },
  {
    id: 15,
    title: 'バックアップシステム構築',
    description: 'データベースの定期バックアップ自動化',
    status: '進行中',
    priority: '高',
    progress: 45,
    assignee: '大野智',
    dueDate: '2024-12-24',
  },
  {
    id: 16,
    title: 'ソーシャルログイン実装',
    description: 'Google、Facebook、Twitterログイン機能の追加',
    status: '未着手',
    priority: '中',
    progress: 0,
    assignee: '櫻井翔',
    dueDate: '2024-12-29',
  },
  {
    id: 17,
    title: 'リアルタイム通知機能',
    description: 'WebSocketを使ったプッシュ通知の実装',
    status: '進行中',
    priority: '高',
    progress: 60,
    assignee: '相葉雅紀',
    dueDate: '2024-12-22',
  },
  {
    id: 18,
    title: 'コードレビュープロセス改善',
    description: 'レビューガイドラインとチェックリストの作成',
    status: '完了',
    priority: '中',
    progress: 100,
    assignee: '二宮和也',
    dueDate: '2024-12-16',
  },
  {
    id: 19,
    title: 'キャッシュ戦略最適化',
    description: 'Redisを使ったキャッシング機構の実装',
    status: '進行中',
    priority: '中',
    progress: 50,
    assignee: '福山雅治',
    dueDate: '2024-12-26',
  },
  {
    id: 20,
    title: 'アクセシビリティ対応',
    description: 'WCAG 2.1 AA準拠のアクセシビリティ改善',
    status: '未着手',
    priority: '低',
    progress: 0,
    assignee: '星野源',
    dueDate: '2025-01-08',
  },
  {
    id: 21,
    title: 'チャット機能開発',
    description: 'ユーザー間のリアルタイムチャット機能',
    status: '進行中',
    priority: '高',
    progress: 35,
    assignee: '菅田将暉',
    dueDate: '2024-12-28',
  },
  {
    id: 22,
    title: 'SEO最適化',
    description: 'メタタグ、構造化データ、サイトマップの改善',
    status: '完了',
    priority: '中',
    progress: 100,
    assignee: '山崎賢人',
    dueDate: '2024-12-14',
  },
  {
    id: 23,
    title: 'ペイメントゲートウェイ統合',
    description: 'Stripeを使った決済機能の実装',
    status: '未着手',
    priority: '高',
    progress: 0,
    assignee: '神木隆之介',
    dueDate: '2025-01-10',
  },
  {
    id: 24,
    title: 'ユーザーフィードバック機能',
    description: 'アプリ内フィードバックフォームとアナリティクス',
    status: '進行中',
    priority: '低',
    progress: 25,
    assignee: '竹内涼真',
    dueDate: '2025-01-03',
  },
];
